TenKUserBundle:
    resource: "@TenKUserBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern:  /
    defaults: { _controller: TenKPwLockerBundle:Default:index }

TenKPwLockerBundle_password_list:
    resource: "@TenKPwLockerBundle/Resources/config/routing.yml"
    prefix:   /passwords

TenKPwLockerBundle_Api:
    resource: "@TenKPwLockerBundle/Resources/config/routingApi.yml"
    prefix:   /api/1.0/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
