homepage:
    pattern:  /
    defaults: { _controller: TenKPwLockerBundle:Default:index }

TenKPwLockerBundle:
    resource: "@TenKPwLockerBundle/Resources/config/routing.yml"
    prefix:   /passwords

TenKPwLockerBundle_Api:
    resource: "@TenKPwLockerBundle/Resources/config/routingApi.yml"
    prefix:   /api/1.0/passwords

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
