<?php

namespace TenK\PwLockerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordRepository extends EntityRepository
{
    public function findAllOrderedByTitle()
    {
        $query =  $this->createQueryBuilder('p')
            ->orderBy('p.title', 'ASC');
        
        return $query->getResult();
    }
    
    /**
     * Add a restriction to a Query to only return objects if the user is
     * permitted to read them. 
     */
    public function userCanReadRestriction(\Doctrine\ORM\QueryBuilder $builder, \TenK\UserBundle\Entity\User $user)
    {
        return $builder->leftJoin('p.shares', 's')
            ->andWhere($builder->expr()->orX(
                $builder->expr()->eq('p.createdBy', ':creator'),
                $builder->expr()->eq('s.toUser', ':toUser')
            ))
            ->setParameters(array('creator' => $user, 'toUser' => $user));
    }
}