<?php

namespace TenK\PwLockerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordRepository extends EntityRepository
{
    public function findAllOrderedByTitle()
    {
        $query =  $this->createQueryBuilder('p')
            ->orderBy('p.title', 'ASC');
        
        return $query->getResult();
    }
}